language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=django==1.6.10
  - DJANGO=django==1.7.5

install:
  - sudo apt-get update
  - sudo apt-get install -y nginx-extras
  - sudo mkdir /webdav
  - sudo chmod -R 0777 /webdav
  - sudo cp ./webdav.conf /etc/nginx/sites-enabled/webdav.conf
  - sudo service nginx restart
  - pip install -q $DJANGO
  - pip install -q flake8
  - pip install -q coveralls coverage
  - python setup.py install

before_script:
  - make flake8

script:
  - make coverage

after_success:
  - make coveralls
